config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path('login/', include('core.login.urls')),
    path('', include('core.homepage.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path
from core.erp.views.category.views import *
from core.erp.views.product.views import *
from core.erp.views.client.views import *
from core.erp.views.sale.views import *
from core.erp.views.tests.views import *
from core.erp.views.dashboard.views import DashboardView
app_name = 'erp'

urlpatterns = [
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # product
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    # client
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/add/', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    # sale
    path('sale/add/', SaleCreateView.as_view(), name='sale_create'),
    path('sale/list/', SaleListView.as_view(), name='sale_list'),
    path('sale/delete/<int:pk>/', SaleDeleteView.as_view(), name='sale_delete'),
    path('sale/update/<int:pk>/', SaleUpdateView.as_view(), name='sale_update'),
    #home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # test
    path('test/', TestView.as_view(), name='test'),
]

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
  {% load static %}

  <body class="hold-transition sidebar-mini layout-navbar-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
      <!-- Header -->
      {% include 'vtc/header.html' %}
      <!-- Sidebar -->
      {% include 'vtc/sidebar.html' %}
      <!-- Content -->

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1></h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item">
                    <a href="{% url 'erp:dashboard' %}">Home</a>
                  </li>
                  <li class="breadcrumb-item">
                    <a href="{{ list_url }}">{{ entity }}</a>
                  </li>
                </ol>
              </div>
            </div>
          </div>
          <!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
          {% if messages %}
          <div class="alert alert-danger alert-dismissible " role="alert">
            <h5><i class="fas fa-ban me-2"></i> Ha ocurrido un error!</h5>
              {% for message in messages %}
                <li>

                  {{ message }}
                  
                </li>
                  
              {% endfor %}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endif %}     
          
          {% block content %}

          {% endblock %}
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->

      <footer class="main-footer">
        <div class="float-right d-none d-sm-block">
          <b>Version</b> 3.2.0
        </div>
        <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
      </footer>

    </div>
  </body>

  
{% endblock %}

templates/vtc/header.html
{% load static %}

<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{% url 'erp:dashboard' %}" class="nav-link">Home</a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="fas fa-users-cog"></i>
        <span class="badge navbar-badge"></span>
      </a>
      <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right" aria-labelledby="userDropdown">
        <li>
          <span class="dropdown-header">Sú último acceso fue {{ request.user.last_login }}</span>
          <div class="dropdown-divider"></div>
        </li>
        <li>
          <a href="#" class="dropdown-item">
            <i class="fas fa-edit me-2"></i> Editar perfil
            <span class="float-end text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
        </li>
        <li>
          <a href="#" class="dropdown-item">
            <i class="fas fa-lock me-2"></i> Editar password
            <span class="float-end text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
        </li>
        <li>
          <a href="#" class="dropdown-item dropdown-footer"><p>Este sistema te permitirá realizar diferentes actividades</p></a>
        </li>
      </ul>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-power-off" aria-hidden="true"></i></a>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

templates/vtc/sidebar.html
{% load static %}

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="{% url 'home' %}" class="brand-link elevation-4">
    <img src="{% static 'img/logo1.jpeg' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8" />
    <span class="brand-text font-weight-light">Facturacion</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user (optional) -->
    <style>
      .rounded-circle-container {
        width: 30px; /* Ajusta el ancho deseado */
        height: 30px; /* Ajusta la altura deseada */
        border-radius: 50%;
        overflow: hidden;
        position: relative;
      }
      
      .rounded-circle-container img {
        width: 100%;
        height: 100%;
        object-fit: cover;
        object-position: center center;
      }
    </style>
    <div class="user-panel mt-3 pb-3 mb-3 d-flex align-items-center">
      <div class="image">
        <div class="rounded-circle-container">
          <img src="{{ user.get_image }}" alt="User Image" />
        </div>
      </div>
      <div class="info">
        <a href="#" class="d-block">{{ user.get_username }}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <a href="{% url 'erp:category_list' %}" class="nav-link">
            <i class="fas fa-truck-loading nav-icon"></i>
            <p>Categorías</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'erp:product_list' %}" class="nav-link">
            <i class="fas fa-boxes nav-icon"></i>
            <p>Productos</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'erp:client_list' %}" class="nav-link">
            <i class="fas fa-users nav-icon"></i>
            <p>Clientes</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'erp:sale_list' %}" class="nav-link">
            <i class="fas fa-shopping-cart nav-icon"></i>
            <p>Ventas</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'erp:test' %}" class="nav-link">
            <i class="fas fa-code nav-icon"></i>
            <p>Test</p>
          </a>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>